services:
  db:
    image: postgres:${POSTGRES_VERSION}-bookworm
    container_name: product-db
    ports:
      - ${PRODUCT_POSTGRES_PORT}:5432
    environment:
      TZ: ${TIME_ZONE}
      PGTZ: ${TIME_ZONE}
      POSTGRES_USER: ${PRODUCT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PRODUCT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PRODUCT_POSTGRES_DB}
    tty: true
    restart: always
    healthcheck:  # コンテナの起動チェック
      test: ["CMD-SHELL", "pg_isready -U $PRODUCT_POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./data:/docker-entrypoint-initdb.d

  pgweb:
    image: sosedoff/pgweb
    container_name: product-pgweb
    ports:
      - ${PRODUCT_PGWEB_PORT}:8081
    environment:
      TZ: ${TIME_ZONE}
      PGTZ: ${TIME_ZONE}
      DATABASE_URL: postgres://${PRODUCT_POSTGRES_USER}:${PRODUCT_POSTGRES_PASSWORD}@db:5432/${PRODUCT_POSTGRES_DB}?sslmode=disable
    restart: always
    depends_on:
      db:
        condition: service_healthy
